stages:
  - build
  - publish

default:
  image: node:20

variables:
  YARN_CACHE_FOLDER: .yarn-cache
  NPM_REGISTRY: "http://eyeguide-repo.essexlg.com:8081/repository/npm-private/"
  NPM_TOKEN: "YWRtaW46VU1waFVQMF9qMTRTMFJTT0FYNng="

.cache: &cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
    policy: pull

# ── Build ────────────────────────────────────────────────────────────────────

build:
  stage: build
  tags:
    - repo-builder
  <<: *cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
    policy: pull-push
  script:
    - node -v
    - cat /home/gitlab-runner/.npmrc || true
    - yarn config list || true
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - packages/*/dist/
      - packages/*/lib/
    expire_in: 1 hour


# ── Publish to npm ───────────────────────────────────────────────────────────

publish:
  stage: publish
  tags:
    - repo-builder
  <<: *cache
  dependencies:
    - build
  script:
    - echo "registry=${NPM_REGISTRY}" > .npmrc
    - echo "//${NPM_REGISTRY#}:_authToken=${NPM_TOKEN}" >> .npmrc
    - yarn lerna publish from-package --yes --no-verify-access --registry ${NPM_REGISTRY}
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master"
